# FASE 6: Secrets per gestione sicura credenziali
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crm-system
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # Base64 encoded values
  # postgres -> cG9zdGdyZXM=
  # admin123 -> YWRtaW4xMjM=
  username: cG9zdGdyZXM=
  password: YWRtaW4xMjM=
  database: Y3Jt  # crm -> Y3Jt
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: crm-system
  labels:
    app: backend
    component: application
type: Opaque
data:
  # JWT secret for authentication
  # your-super-secret-jwt-key-fase6-k8s -> eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mYXNlNi1rOHM=
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mYXNlNi1rOHM=
---
# ConfigMap per variabili non sensibili
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: crm-system
  labels:
    app: backend
    component: configuration
data:
  NODE_ENV: "production"
  PORT: "4001"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "crm"
  FRONTEND_URL: "http://192.168.1.29/crm"
  # PostgreSQL connection settings
  DB_CONNECTION_TIMEOUT: "30000"
  DB_POOL_SIZE: "10"
  # Application settings
  CORS_ORIGIN: "http://192.168.1.29"
  API_PREFIX: "/api"
