# FASE 6: Persistent Volume Claim per PostgreSQL (FIXED per k3s)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: crm-system
  labels:
    app: postgres
    component: database
    storage-type: persistent
spec:
  storageClassName: local-path  # k3s default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # RIMOSSO selector che causava problemi con local-path provisioner
