# FASE 6: Persistent Volume Claim per PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: crm-system
  labels:
    app: postgres
    component: database
    storage-type: persistent
spec:
  storageClassName: local-path  # k3s default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Selector per identificare il volume (opzionale)
  # Useful per riferimenti specifici se necessario
  selector:
    matchLabels:
      app: postgres
---
# Opzionale: StorageClass personalizzata se necessario
# Per ora usiamo local-path di k3s che funziona perfettamente
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: crm-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  # Path di default k3s: /opt/local-path-provisioner
  # Manteniamo default per compatibilità
  nodePath: "/opt/local-path-provisioner"
